desc: "减小模型，增大k，损失函数改成交叉熵"
batch_size: 4
epochs: 100
k: 16
test_k: 16
init: true
debug: true
root_dir: &root_dir /home/4T/zcr/dataset/Dataset_BUSI
model:
  name: universeg_res.universeg.UniverSeg
  args:
    channels: [64, 64, 64, 64, 64]
    num_layers: [1, 1, 1, 1, 1]
    in_channels: [1, 2]
    act: LeakyReLU

trainset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: labeled_all.txt
    mode: train

testset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: test.txt
    mode: test

validset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: val.txt
    mode: test

criterion:
  name: spgutils.focalloss.BinaryFocalLoss
  args:
    gamma: 0

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001

scheduler:
  name: torch.optim.lr_scheduler.ReduceLROnPlateau
  args:
    mode: max
    factor: 0.85
    patience: 3
