batch_size: 8
epochs: 50
model:
  name: net.eunet.EUnet
  args:
    ch_out: 1

trainset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: d:/data/Dataset_BUSI
    image_names_path: d:/data/Dataset_BUSI/labeled20.txt
    mode: train

testset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: d:/data/Dataset_BUSI
    image_names_path: d:/data/Dataset_BUSI/unlabeled20.txt
    mode: test

criterion:
  name: spgutils.focalloss.BinaryFocalLoss

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001

scheduler:
  name: torch.optim.lr_scheduler.StepLR
  args:
    step_size: 1
    gamma: 0.95