batch_size: 8
epochs: 50
model:
  name: net.eunet.EUnet
  args:
    ch_out: 1

trainset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: /Dataset_BUSI
    image_names_path: /Dataset_BUSI/labeled20.txt
    mode: train

trainset_u:
  name: datasetBUSI.w_s.WeakStrongBUSI
  args:
    root_dir: /Dataset_BUSI
    image_names_path: /Dataset_BUSI/unlabeled20.txt
    mode: train



testset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: /Dataset_BUSI
    image_names_path: /Dataset_BUSI/test.txt
    mode: test

criterion:
  name: spgutils.focalloss.BinaryFocalLoss
  args:
    reduction:

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001

scheduler:
  name: torch.optim.lr_scheduler.StepLR
  args:
    step_size: 1
    gamma: 0.95