batch_size: 8
epochs: 100
root_dir: &root_dir /home/4T/zcr/dataset/Dataset_BUSI
model:
  name: net.eunet.EUnet
  args:
    ch_out: 1

trainset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: *root_dir
    image_names_path: labeled_all.txt
    mode: train

testset:
  name: datasetBUSI.mask_busi.MaskBUSI
  args:
    root_dir: *root_dir
    image_names_path: test.txt
    mode: test

criterion:
  # name: spgutils.focalloss.BinaryFocalLoss
  name: spgutils.focalloss.BinaryFocalLoss
  args:
    gamma: 1

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001

scheduler:
  name: torch.optim.lr_scheduler.StepLR
  args:
    step_size: 1
    gamma: 0.99