desc: "first"
batch_size: 8
epochs: 100
init: true
debug: true
all_metric: true
model:
  name: unet.aaunet.AAUNet
  args:
    channels: [32, 64, 128, 256, 512]
    in_channels: 3

trainset:
  name: lxb.dataset.DataSets.BreastDataset
  args:
    path: lxb/data/train
    phase: train

testset:
  name: lxb.dataset.DataSets.BreastDataset
  args:
    path: lxb/data/val
    phase: test

criterion:
  name: spgutils.focalloss.BinaryFocalLoss
  args:
    gamma: 0

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.00005

scheduler:
  name: torch.optim.lr_scheduler.StepLR
  args:
    step_size: 1
    gamma: 0.97
