desc: "big unet"
batch_size: 8
epochs: 100
init: true
root_dir: &root_dir /Dataset_BUSI
model:
  name: unet.unet.Unet
  args:
    channels: [ 64, 128, 256, 512,  1024 ]

trainset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: labeled_all.txt
    mode: train

testset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: test.txt
    mode: test

validset:
  name: datasetBUSI.mask_busi_single.MaskBUSISingle
  args:
    root_dir: *root_dir
    image_names_path: val.txt
    mode: test

criterion:
  name: spgutils.focalloss.BinaryFocalLoss
  args:
    gamma: 1

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001

scheduler:
  name: torch.optim.lr_scheduler.ReduceLROnPlateau
  args:
    mode: max
    factor: 0.85
    patience: 3
