# big leakyrelu
dataset_path: /data/litong/llm_aug-copy/Dataset_BUSI
# nclass: 1

# training
epochs: 110
valid_start_epoch: 40
batch_size: 4
save_path: ./unet_big

opt:
  name: adam
  lr: 0.001

scheduler:
  name: plat
  verbose: True
  factor: 0.85
  mode: max

criterion:
  - name: bce
    weight: 1

model:
  name: unet
  in_channels: 3
  n_classes: 1
  out_channels: [64, 128, 256, 512, 1024]
  act: leakyrelu
