# 20+leakyrel+multistep
dataset:
  name: mask
  root_dir: /data/litong/llm_aug-copy/Dataset_BUSI
  train_file: labeled20.txt
# training
epochs: 110
valid_start_epoch: 40
batch_size: 8
save_path: ./unet_small

opt:
  name: adam
  lr: 0.0002

scheduler:
  name: multistep
  verbose: True
  milestones: [40, 50, 70, 100]
  gamma: 0.7

criterion:
  - name: bce
    weight: 1

model:
  name: unet
  in_channels: 3
  n_classes: 1
  out_channels: [32, 64, 128, 256, 512]
  act: leakyrelu
